### ISSUE TITLE
ebook-convert: Missing library

### ISSUE THREAD

**Issue by JayBraker** [lmorel3/calibre-alpine#1]
Hi, just wanted to let you know that rn this container seems to be missing an essential library (at least for the ebook-converter component).

```bash
 # ebook-convert /tmp/ebooktitle.epub /tmp/ebooktitle.pdf
1% Converting input to HTML...
InputFormatPlugin: EPUB Input running
on /tmp/ebooktitle.epub
Parsing all content...
34% Running transforms on e-book...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Creating PDF Output...
67% Running PDF Output plugin
Splitting markup on page breaks and flow limits, if any...
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/ebooks/conversion/cli.py", line 391, in main
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1270, in run
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 191, in convert
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 253, in convert_text
  File "site-packages/calibre/ebooks/pdf/render/from_html.py", line 17, in <module>
ImportError: libXcomposite.so.1: cannot open shared object file: No such file or directory
```

**Comment by lmorel3** [comment]
Wow, it's been a while. Thanks for your contribution. I hope this small project is useful for you.. I don't use it anymore :)

**Comment by JayBraker** [comment]
Haha well more of a oneshot: I needed to quickly convert an epub so I appreciate a good container with the right tooling.

Tysm
